#
# Makefile
# uralbash, 2016-02-22 18:09
#

all:
	git submodule add https://github.com/jszakmeister/markdown2ctags.git submodules/markdown2ctags/
	git submodule add https://github.com/jszakmeister/rst2ctags.git submodules/rst2ctags/


# vim:ft=make
#
